[package]
name = "motocare"
version = "0.1.0"
description = "MotoCare CMS desktop application"
authors = ["MotoCare"]
edition = "2021"

[lib]
name = "motocare_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-updater = "2"
