<script setup lang="ts">
import { Edit3, Plus, ShieldCheck } from '@lucide/vue'
import type { Employee, PagedResult, UserAccount } from '~/types/api'
import { formatDate } from '~/utils/format'

const api = useApi(); const toast = useToast()
const users = ref<UserAccount[]>([]); const employees = ref<Employee[]>([])
const modalOpen = ref(false); const saving = ref(false); const editing = ref<UserAccount>()
const form = reactive({ username: '', password: '', fullName: '', employeeId: '', role: 'Employee' as 'Admin'|'Manager'|'Employee', isActive: true })
const employeeOptions = computed(() => [{ code: '', name: 'Không liên kết nhân viên' }, ...employees.value.map(x => ({ code: x.id, name: `${x.fullName} · ${x.employeeCode}` }))])
const load = async () => { const [u,e] = await Promise.all([api.request<UserAccount[]>('/users'), api.request<PagedResult<Employee>>('/employees?pageSize=200')]); users.value=u; employees.value=e.items }
const openForm = (item?: UserAccount) => { editing.value=item; Object.assign(form,{ username:item?.username||'', password:'', fullName:item?.fullName||'', employeeId:item?.employeeId||'', role:item?.roles[0]||'Employee', isActive:item?.isActive??true }); modalOpen.value=true }
const save = async () => { saving.value=true; try { if(editing.value) await api.request(`/users/${editing.value.id}`,{method:'PUT',body:{fullName:form.fullName,employeeId:form.employeeId||null,role:form.role,isActive:form.isActive,newPassword:form.password||null}}); else await api.request('/users',{method:'POST',body:{username:form.username,password:form.password,fullName:form.fullName,employeeId:form.employeeId||null,roles:[form.role]}}); toast.success('Đã lưu tài khoản',form.fullName); modalOpen.value=false; await load() } finally { saving.value=false } }
const roleLabel=(role:string)=>role==='Admin'?'Admin':role==='Manager'?'Quản lý':'Nhân viên'
onMounted(load)
</script>
<template><div class="page"><div class="page-header"><div><h1 class="page-title">Tài khoản & quyền</h1><p class="page-subtitle">Quản lý ba vai trò: Admin, Quản lý và Nhân viên.</p></div><button class="btn btn-accent" @click="openForm()"><Plus :size="17"/>Thêm tài khoản</button></div><section class="card"><div class="table-wrap"><table v-if="users.length" class="data-table"><thead><tr><th>Tài khoản</th><th>Họ tên</th><th>Vai trò</th><th>Đăng nhập gần nhất</th><th>Trạng thái</th><th class="text-right">Thao tác</th></tr></thead><tbody><tr v-for="item in users" :key="item.id"><td class="mono">{{item.username}}</td><td class="cell-main">{{item.fullName}}</td><td><AppBadge :tone="item.roles[0]==='Admin'?'danger':item.roles[0]==='Manager'?'warning':'neutral'">{{roleLabel(item.roles[0]||'')}}</AppBadge></td><td>{{formatDate(item.lastLoginAt,true)}}</td><td><AppBadge :tone="item.isActive?'success':'neutral'">{{item.isActive?'Hoạt động':'Tạm khóa'}}</AppBadge></td><td class="text-right"><button class="icon-btn" title="Sửa tài khoản" @click="openForm(item)"><Edit3 :size="15"/></button></td></tr></tbody></table><AppEmpty v-else :icon="ShieldCheck" title="Chưa có tài khoản" message="Tạo tài khoản và gán một trong ba vai trò."/></div></section><AppModal :open="modalOpen" :title="editing?'Cập nhật tài khoản':'Thêm tài khoản'" @close="modalOpen=false"><form id="user-form" class="form-grid" @submit.prevent="save"><div class="field"><label>Tên đăng nhập *</label><input v-model.trim="form.username" class="input" :disabled="!!editing" required/></div><div class="field"><label>{{editing?'Mật khẩu mới':'Mật khẩu *'}}</label><input v-model="form.password" class="input" type="password" :required="!editing" minlength="8" :placeholder="editing?'Để trống nếu không đổi':''"/></div><div class="field span-2"><label>Họ và tên *</label><input v-model.trim="form.fullName" class="input" required/></div><div class="field"><label>Vai trò *</label><select v-model="form.role" class="select"><option value="Admin">Admin</option><option value="Manager">Quản lý</option><option value="Employee">Nhân viên</option></select></div><div class="field"><label>Liên kết nhân viên</label><AppSearchSelect v-model="form.employeeId" :options="employeeOptions" :clearable="false"/></div><div v-if="editing" class="field span-2"><label>Trạng thái tài khoản</label><div class="account-status"><label><input v-model="form.isActive" type="radio" :value="true"/> Hoạt động</label><label><input v-model="form.isActive" type="radio" :value="false"/> Tạm khóa</label></div></div></form><template #footer><button class="btn btn-secondary" @click="modalOpen=false">Hủy</button><button class="btn btn-primary" form="user-form" :disabled="saving">Lưu tài khoản</button></template></AppModal></div></template>

<style scoped>.account-status{display:flex;gap:8px;flex-wrap:wrap}.account-status label{display:flex;align-items:center;gap:6px;padding:9px 12px;border:1px solid var(--line);border-radius:9px}@media(max-width:480px){.account-status label{flex:1 1 130px;justify-content:center}}</style>
